debug: false
uuid: 5d7c858c-188f-4ba3-84a5-0a0292430085
token_id: 4dKJzWM6pEmoPVk1
token: eyJpdiI6Ikd2N1R3RXVxeVZQUnlUTi9hZFNBeXc9PSIsInZhbHVlIjoiS2JNRHRiWDRNc3RRWDA3OGtOVDNhNjNadWFKaUIvM3o2NzNxT252U05FOFY5U1pBdzZZZWNJSDRjd2VldkhOVjliWHlDOFJyL2w5M3dpdkZSbmpNQ3AyKzhCL1R1Yy9RaWFRZkI0cGN6ckU9IiwibWFjIjoiYzI0MmRlZGY3YWM2NjVlMTAwZTUwYTRjMGE0ZjM2OTQ4ZGVhYzExODk3MTgzNTY5Y2ZhZDY2MTkxMjVhYTQyMCIsInRhZyI6IiJ9
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/127.0.0.1/fullchain.pem
    key: /etc/letsencrypt/live/127.0.0.1/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: "http://pterodactyl-panel"
docker:
  network:
    name: host
    network_mode: host
