debug: false
uuid: f2b6f48d-1449-4f7a-96d5-69ddbe6eac8c
token_id: Yt7fFgg8lbbYQpTI
token: E6oxWHv0MJUpRpo4guFtiW5CJnBR6anpUWpQlDMFvgIij5OfypiBwfLNcncKopRY
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/127.0.0.1/fullchain.pem
    key: /etc/letsencrypt/live/127.0.0.1/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: "http://pterodactyl-panel"
docker:
  network:
    name: host
    network_mode: host
